source "${HOME}/.zgenom/zgenom.zsh"
source "${HOME}/.zsh/plugins.sh"
source "${HOME}/.zsh/alias.sh"
source "${HOME}/.zsh/environment.sh"
source "${HOME}/.zsh/function.sh"
source "${HOME}/.zsh/runcom.sh"
source "${HOME}/.zsh/specific.sh"
